DROP TABLE IF EXISTS CRM_ORDER;
DROP TABLE IF EXISTS CRM_ORDER_ITEM;
DROP TABLE IF EXISTS CRM_PRODUCT;
DROP TABLE IF EXISTS CRM_PRODUCER;
DROP TABLE IF EXISTS CRM_PRODUCT_PRODUCER;


CREATE TABLE CRM_ORDER
(
    ORDER_ID SERIAL,
    ORDER_NUMBER VARCHAR(20),
    ORDER_USER VARCHAR(20),
    ORDER_DATE TIMESTAMP,
    PRIMARY KEY(ORDER_ID)
);

CREATE TABLE CRM_ORDER_ITEM
(
    ORDER_ITEM_ID SERIAL,
    ORDER_ID INTEGER,
    PRODUCT_ID INTEGER,
    PRICE DECIMAL,
    QUANTITY INTEGER,
    PRIMARY KEY(ORDER_ITEM_ID)
);

CREATE TABLE CRM_PRODUCT
(
    PRODUCT_ID SERIAL,
    PRODUCT_NAME VARCHAR(100),
    PRIMARY KEY(PRODUCT_ID)
);

CREATE TABLE CRM_PRODUCER
(
    PRODUCER_ID SERIAL,
    PRODUCER_NAME VARCHAR(100),
    PRIMARY KEY(PRODUCER_ID)
);

CREATE TABLE CRM_PRODUCT_PRODUCER
(
    PRODUCT_ID INTEGER,
    PRODUCER_ID INTEGER,
    PRIMARY KEY(PRODUCT_ID, PRODUCER_ID)
);